tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'homebrew/science'
tap 'neovim/homebrew-neovim'
tap 'aspnet/k'
tap 'thoughtbot/formulae'
tap 'karan/karan'
tap 'jlhonora/lsusb'

brew 'eigen'
brew 'opencv'

brew 'veclibfort'

brew 'mono'
brew 'kvm'

brew '--HEAD neovim'

# install GNU core utilities (those that come with OS X are outdated)
# don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew 'coreutils'
# install some other useful utilities like `sponge`
brew 'moreutils'
# install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew 'findutils'
# install GNU `sed`, overwriting the built-in `sed`
brew 'gnu-sed', args: ['default-names']

# install Bash 4
# note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
brew 'bash'
brew 'bash-completion'

brew 'mongodb'
brew 'reattach-to-user-namespace'
brew 'ansifilter'
brew 'wget', args: ['enable-iri']
brew 'rcm'
brew 'gitsh'
brew 'liftoff'
brew 'gitignore'
brew 'spark'
brew 'zmap'
brew 'fish'
brew 'zsh'
brew 'zsh-completions'
brew 'weechat', args: ['with-python', 'with-perl']
brew 'irssi'
brew 'wireshark', args: ['with-qt']
brew 'lsusb'

# install RingoJS and Narwhal
# note that the order in which these are installed is important
# see http://git.io/brew-narwhal-ringo.
brew 'ringojs'
brew 'narwhal'

brew 'ant'
brew 'maven'
brew 'rbenv'

brew 'doxygen'

# install more recent versions of some OS X tools
brew 'vim', args: ['override-system-vi', 'with-lua', 'with-perl', 'with-python3', 'with-ruby']
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/screen'

brew 'python'
brew 'python3'
brew 'ghc'
brew 'cabal-install'

brew 'mysql'
brew 'redis'
brew 'boot2docker'

# install XML libs
brew 'libxml2'
brew 'libxslt'

brew 'tmux'
brew 'nginx'
brew 'pow'
brew 'ctags'
brew 'llvm'
brew 'gs'
brew 'autossh'
brew 'graphviz'
brew 'the_silver_searcher'
brew 'ack'
brew 'bfg'
brew 'foremost'
brew 'svn'
brew 'git'
brew 'git-flow'
brew 'darcs'
brew 'hashpump'
brew 'imagemagick', args: ['with-webp', 'with-x11']
brew 'lynx'
brew 'nmap'
brew 'node'
brew 'p7zip'
brew 'pv'
brew 'rename'
brew 'rhino'
brew 'sqlite'
brew 'sqlmap'
brew 'tree'
brew 'ucspi-tcp'
brew 'webkit2png'
brew 'xpdf'
brew 'zopfli'
brew 'ffmpeg'
brew 'mplayer'
brew 'mplayershell'
brew 'youtube-dl'
brew 'homebrew/versions/lua52'

cask 'xquartz'
cask 'dropbox'
cask 'caffeine'
cask 'tiled'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'google-hangouts'
cask 'skype'
cask 'send-to-kindle'
cask 'imagealpha'
cask 'imageoptim'
cask 'iterm2'
cask 'totalterminal'
cask 'macvim'
cask 'flux'
cask 'miro-video-converter'
cask 'opera'
cask 'opera-developer'
cask 'opera-next'
cask 'sublime-text'
cask 'sublime-text3'
cask 'heroku-toolbelt'
cask 'the-unarchiver'
cask 'torbrowser'
cask 'transmission'
cask 'transmit'
cask 'virtualbox'
cask 'vlc'
cask 'audacity'
cask 'handbrake'
cask 'github'
cask 'sourcetree'
cask 'lighttable'
cask 'vagrant'
cask 'atom'
cask 'alfred'
cask 'evernote'
cask 'poedit'
cask 'sequel-pro'
cask 'teamviewer'
cask 'clock'
cask 'toggldesktop'
cask 'totalspaces'
cask 'istat-menus'
cask 'nvalt'
cask 'skitch'
cask 'bittorrent-sync'
cask 'textmate'
cask 'anvil'
cask 'commandq'
cask 'mplayerx'
cask 'onepassword'
cask 'adium'
cask 'superduper'
cask 'karabiner'
cask 'seil'
cask 'slack'
cask 'screenhero'
cask 'mou'
cask 'torbrowser'
cask 'java'
cask 'caskroom/versions/java7'
cask 'intellij-idea-ce'
cask 'aquamacs'
cask 'arduino'
cask 'boot2docker'
cask 'brackets'
cask 'breach'
cask 'calibre'
cask 'daisydisk'
cask 'forklift'
cask 'genymotion'
cask 'graphviz'
cask 'kindle'
cask 'kitematic'
cask 'komanda'
cask 'macdown'
cask 'pg-commander'
cask 'pgadmin3'
cask 'rubymine'
cask 'slate'
cask 'steam'
cask 'tunnelbear'
cask 'wineskin-winery'
cask 'postgres'
# cask 'spotify'
# cask 'eclipse-ide'
# cask 'android-studio'

# add /opt/homebrew-cask/Caskroom
# to aflred Search Scopes manually

cask 'font-vollkorn'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-comic-neue'
cask 'font-courier-prime'
cask 'font-source-serif-pro'
