set visualbell                " no sounds

" window size
set lines=42
set columns=100

set guioptions+=e
set guioptions+=c             " use console dialogs instead of gui popups
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=b
set guioptions-=l
set guioptions-=L
set guioptions-=T

set guicursor+=n-v-c:blinkon0

set showtabline=0             " never show line with tab page labels
set noballooneval             " dont show this crazy distracting thing

if has("gui_gtk2")
  set guifont=Source\ Code\ Pro\ 10
elseif has("gui_macvim")
  set guifont=Menlo\ Regular:h11
elseif has("gui_win32")
  set guifont=Consolas:h11:cANSI
endif

" set transparency=20

" start in fullscreen mode
" set fuopt+=maxhorz
" set fu

