export GOPATH=/usr/local/go/bin

export LANG=en_US.UTF-8
export LC_ALL=$LANG

# Specify your defaults in this environment variable
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/etc/Caskroom"

source ~/.dotsecrets/secret_tokens
