export PATH="$HOME/.rbenv/shims:/$HOME/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/$HOME/.local/bin:/usr/games:/usr/local/games:$HOME/.cabal/bin:$HOME/Library/Haskell/bin:./node_modules/.bin"

set -o vi

export GREP_COLOR='1;33'

if [ -n "$DISPLAY" -a "$TERM" = "xterm" ]; then
  export TERM=xterm-256color
fi

export EDITOR=vim

if [[ -n $SSH_CONNECTION ]]; then
  # nothing to do here for now
else
  export VISUAL=nvim
fi

# load additional completions
fpath=(/usr/local/share/zsh-completions $fpath)

# use vi key bindings
bindkey -v    

# search backward incrementally for a specified string
bindkey '^r' history-incremental-search-backward

# emacs style movements
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
bindkey '^[[1;5C' emacs-forward-word
bindkey '^[[1;5D' emacs-backward-word

# oh my zsh

export ZSH=$HOME/.oh-my-zsh

DISABLE_UPDATE_PROMPT=true

plugins=(
  ant fasd battery brew cap cabal coffee docker cp gem
  git github heroku history history-substring-search jruby knife lein
  node npm osx perl python rails rake rsync ruby rvm scala tmux
  tmuxinator torrent vagrant vundle redis-cli web-search bower
)

source $ZSH/oh-my-zsh.sh

source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

source $HOME/.zsh-history-substring-search/zsh-history-substring-search.zsh
source $HOME/.zsh-autosuggestions/autosuggestions.zsh

export AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=11'

# enable autosuggestions automatically
zle-line-init() {
  zle autosuggest-start
}
zle -N zle-line-init

# use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
# zsh-autosuggestions is designed to be unobtrusive)
bindkey '^T' autosuggest-toggle
bindkey '^f' vi-forward-word

# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

autoload -U promptinit && promptinit

# disable annoying autocorrect feature
unsetopt correct_all

# auto predict
autoload predict-on
autoload predict-off

# on/off zsh autopredict
zle -N predict-on
zle -N predict-off
bindkey '^X1' predict-on
bindkey '^X2' predict-off

export DOTFILES=$HOME/.dotfiles

# load custom functions & aliases
source $DOTFILES/index

# powerline prompt (slow)
# source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# pure prompt
autoload -U promptinit && promptinit
prompt pure

# setup rbenv
eval "$(rbenv init - --no-rehash)"

# setup default docker host
eval "$(docker-machine env default)"

# use overcommit for all repositories you create/clone (carefull cuz of brew)
# export GIT_TEMPLATE_DIR=`overcommit --template-dir`

export NVM_DIR=~/.nvm
source ~/.nvm/nvm.sh
