#!/bin/sh

# clone Vundle.vim if its not there already
if [ ! -e $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/vundle
fi

# install vim plugins
vim -u $HOME/.vim/vundle.vim +PluginInstall +qa
cd $HOME/.vim/bundle/tern_for_vim
npm install
cd -
