{:repl {:plugins [[cider/cider-nrepl "0.15.0-SNAPSHOT"]
                  [refactor-nrepl "2.3.0-SNAPSHOT"]]
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.12"]]}}

{:user {:plugins [[lein-dotenv "1.0.0"]
                  [lein-exec "0.3.5"]
                  [lein-pprint "1.1.2"]
                  [lein-kibit "0.1.3"]
                  [jonase/eastwood "0.2.3"]
                  [com.jakemccrary/lein-test-refresh "0.18.1"]
                  [lein-autoexpect "1.9.0"]
                  [lein-ancient "0.6.10"]
                  [lein-annotations "0.1.0"]
                  [lein-autoreload "0.1.1"]
                  [lein-bikeshed "0.4.1"]
                  [lein-cprint "1.2.0"]
                  [lein-ns-dep-graph "0.1.0-SNAPSHOT"]
                  [lein-vanity "0.2.0"]
                  [lein-ring "0.11.0"]
                  [lein-cloudbees "1.0.5"]
                  [org.clojure/tools.trace "0.7.9"]
                  [venantius/ultra "0.5.1"]]
        }
 }
