{:user {:plugins [[cider/cider-nrepl "0.9.1"]
                  [lein-exec "0.3.4"]
                  [lein-pprint "1.1.1"]
                  [lein-ancient "0.6.0-SNAPSHOT"]
                  [lein-annotations "0.1.0"]
                  [lein-autoreload "0.1.0"]
                  [lein-bikeshed "0.1.7"]
                  [lein-cprint "1.0.0"]
                  [lein-ns-dep-graph "0.1.0-SNAPSHOT"]
                  [lein-vanity "0.2.0"]
                  [lein-ring "0.8.11"]
                  [lein-cloudbees "1.0.5"]
                  [venantius/ultra "0.4.0"]
                  [org.clojure/tools.trace "0.7.8"]]
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.7"]]}}
